### PR TITLE
add BeautifulSoup 4 compatibility

### PR DESCRIPTION
**Pull request by noraj**

### CODE REVIEW

**Comment by noraj** [comment]
For example on Archlinux BeautifulSoup is only provided as `python2-beautifulsoup4` on official repository. `python2-beautifulsoup3` can be only obtained from AUR or blackarch repository.

**Comment by noraj** [comment]
PS : I tested with BeautifulSoup 4 and it worked exaclty like with BeautifoulSoup 3 as far as my scan did.

**Comment by noraj** [comment]
see https://github.com/BlackArch/blackarch/issues/2131, this is fixing this error on archlinux:

```python
Traceback (most recent call last):                                                                                                                   
  File "wascan.py", line 37, in <module>                                                                                                             
    from lib.handler.crawler import *                                                                                                                
  File "/usr/share/wascan/lib/handler/crawler.py", line 10, in <module>                                                                              
    from lib.request.crawler import SCrawler                                                                                                         
  File "/usr/share/wascan/lib/request/crawler.py", line 15, in <module>                                                                              
    from BeautifulSoup import BeautifulSoup                                                                                                          
ImportError: No module named BeautifulSoup
```

**Comment by m4ll0k** [comment]
@noraj thanks for your contribution

**Pull request merged**
